export {
    FLAG_DEFER, FLAG_STABLE, FLAG_SETUP, FLAG_STALE,
    FLAG_PENDING, FLAG_DISPOSED, FLAG_LOADING, FLAG_ERROR,
    FLAG_DERIVED, FLAG_EQUAL, FLAG_WEAK, FLAG_INIT,
    OPT_DEFER, OPT_STABLE, OPT_SETUP, OPT_WEAK,
    OPTIONS,
    IDLE,
    subscribe,
    startEffect,
} from "./core/signal.js";
